const COUNTRY_OPTIONS = [
  { code: 'US', englishName: 'United States', chineseName: '美国' },
  { code: 'CA', englishName: 'Canada', chineseName: '加拿大' },
  { code: 'MX', englishName: 'Mexico', chineseName: '墨西哥' },
  { code: 'GB', englishName: 'United Kingdom', chineseName: '英国' },
  { code: 'DE', englishName: 'Germany', chineseName: '德国' },
  { code: 'FR', englishName: 'France', chineseName: '法国' },
  { code: 'IT', englishName: 'Italy', chineseName: '意大利' },
  { code: 'ES', englishName: 'Spain', chineseName: '西班牙' },
  { code: 'PT', englishName: 'Portugal', chineseName: '葡萄牙' },
  { code: 'NL', englishName: 'Netherlands', chineseName: '荷兰' },
  { code: 'BE', englishName: 'Belgium', chineseName: '比利时' },
  { code: 'AT', englishName: 'Austria', chineseName: '奥地利' },
  { code: 'CH', englishName: 'Switzerland', chineseName: '瑞士' },
  { code: 'SE', englishName: 'Sweden', chineseName: '瑞典' },
  { code: 'NO', englishName: 'Norway', chineseName: '挪威' },
  { code: 'DK', englishName: 'Denmark', chineseName: '丹麦' },
  { code: 'FI', englishName: 'Finland', chineseName: '芬兰' },
  { code: 'PL', englishName: 'Poland', chineseName: '波兰' },
  { code: 'CZ', englishName: 'Czech Republic', chineseName: '捷克' },
  { code: 'HU', englishName: 'Hungary', chineseName: '匈牙利' },
  { code: 'GR', englishName: 'Greece', chineseName: '希腊' },
  { code: 'IE', englishName: 'Ireland', chineseName: '爱尔兰' },
  { code: 'RO', englishName: 'Romania', chineseName: '罗马尼亚' },
  { code: 'BG', englishName: 'Bulgaria', chineseName: '保加利亚' },
  { code: 'HR', englishName: 'Croatia', chineseName: '克罗地亚' },
  { code: 'RS', englishName: 'Serbia', chineseName: '塞尔维亚' },
  { code: 'SI', englishName: 'Slovenia', chineseName: '斯洛文尼亚' },
  { code: 'SK', englishName: 'Slovakia', chineseName: '斯洛伐克' },
  { code: 'UA', englishName: 'Ukraine', chineseName: '乌克兰' },
  { code: 'EE', englishName: 'Estonia', chineseName: '爱沙尼亚' },
  { code: 'LV', englishName: 'Latvia', chineseName: '拉脱维亚' },
  { code: 'LT', englishName: 'Lithuania', chineseName: '立陶宛' },
  { code: 'RU', englishName: 'Russia', chineseName: '俄罗斯' },
  { code: 'CN', englishName: 'China', chineseName: '中国' },
  { code: 'JP', englishName: 'Japan', chineseName: '日本' },
  { code: 'KR', englishName: 'South Korea', chineseName: '韩国' },
  { code: 'IN', englishName: 'India', chineseName: '印度' },
  { code: 'ID', englishName: 'Indonesia', chineseName: '印度尼西亚' },
  { code: 'TH', englishName: 'Thailand', chineseName: '泰国' },
  { code: 'VN', englishName: 'Vietnam', chineseName: '越南' },
  { code: 'PH', englishName: 'Philippines', chineseName: '菲律宾' },
  { code: 'MY', englishName: 'Malaysia', chineseName: '马来西亚' },
  { code: 'SG', englishName: 'Singapore', chineseName: '新加坡' },
  { code: 'HK', englishName: 'Hong Kong', chineseName: '香港' },
  { code: 'TW', englishName: 'Taiwan', chineseName: '台湾' },
  { code: 'BD', englishName: 'Bangladesh', chineseName: '孟加拉国' },
  { code: 'PK', englishName: 'Pakistan', chineseName: '巴基斯坦' },
  { code: 'TR', englishName: 'Turkey', chineseName: '土耳其' },
  { code: 'SA', englishName: 'Saudi Arabia', chineseName: '沙特阿拉伯' },
  { code: 'AE', englishName: 'United Arab Emirates', chineseName: '阿联酋' },
  { code: 'IL', englishName: 'Israel', chineseName: '以色列' },
  { code: 'EG', englishName: 'Egypt', chineseName: '埃及' },
  { code: 'IR', englishName: 'Iran', chineseName: '伊朗' },
  { code: 'IQ', englishName: 'Iraq', chineseName: '伊拉克' },
  { code: 'QA', englishName: 'Qatar', chineseName: '卡塔尔' },
  { code: 'KW', englishName: 'Kuwait', chineseName: '科威特' },
  { code: 'AU', englishName: 'Australia', chineseName: '澳大利亚' },
  { code: 'NZ', englishName: 'New Zealand', chineseName: '新西兰' },
  { code: 'BR', englishName: 'Brazil', chineseName: '巴西' },
  { code: 'AR', englishName: 'Argentina', chineseName: '阿根廷' },
  { code: 'CO', englishName: 'Colombia', chineseName: '哥伦比亚' },
  { code: 'CL', englishName: 'Chile', chineseName: '智利' },
  { code: 'PE', englishName: 'Peru', chineseName: '秘鲁' },
  { code: 'VE', englishName: 'Venezuela', chineseName: '委内瑞拉' },
  { code: 'ZA', englishName: 'South Africa', chineseName: '南非' },
  { code: 'NG', englishName: 'Nigeria', chineseName: '尼日利亚' },
  { code: 'KE', englishName: 'Kenya', chineseName: '肯尼亚' },
  { code: 'MA', englishName: 'Morocco', chineseName: '摩洛哥' }
] as const

export const SUPPORTED_PROXY_COUNTRIES = [
  ...COUNTRY_OPTIONS.map((country) => ({
    code: country.code,
    label: `${country.chineseName} (${country.code})`
  })),
  { code: 'ROW', label: '其他地区 (ROW)' }
] as const
