import { cn } from '@/lib/utils'

const STYLES: Record<string, string> = {
  queued: 'bg-slate-100 text-slate-700',
  running: 'bg-amber-100 text-amber-800',
  completed: 'bg-emerald-100 text-emerald-800',
  completed_with_issues: 'bg-amber-100 text-amber-800',
  high: 'bg-rose-100 text-rose-800',
  medium: 'bg-amber-100 text-amber-800',
  low: 'bg-slate-100 text-slate-700',
  published: 'bg-emerald-100 text-emerald-800',
  partialFailed: 'bg-orange-100 text-orange-800',
  failed: 'bg-rose-100 text-rose-800',
  success: 'bg-emerald-100 text-emerald-800',
  error: 'bg-rose-100 text-rose-800',
  warning: 'bg-amber-100 text-amber-800',
  skipped: 'bg-slate-100 text-slate-700',
  draft: 'bg-slate-100 text-slate-700',
  configured: 'bg-emerald-100 text-emerald-800',
  partial: 'bg-amber-100 text-amber-800',
  missing: 'bg-rose-100 text-rose-800',
  review: 'bg-sky-100 text-sky-800',
  comparison: 'bg-indigo-100 text-indigo-800',
  guide: 'bg-violet-100 text-violet-800',
  hero: 'bg-amber-100 text-amber-800',
  gallery: 'bg-teal-100 text-teal-800',
  manual: 'bg-zinc-100 text-zinc-800',
  partnerboost_amazon: 'bg-orange-100 text-orange-800',
  partnerboost_dtc: 'bg-cyan-100 text-cyan-800',
  resolveAffiliateLink: 'bg-slate-100 text-slate-700',
  scrapeProductFacts: 'bg-sky-100 text-sky-800',
  persistMediaAssets: 'bg-amber-100 text-amber-800',
  normalizeProduct: 'bg-emerald-100 text-emerald-800',
  mineHardcoreIntents: 'bg-violet-100 text-violet-800',
  resolveVideoEntities: 'bg-blue-100 text-blue-800',
  extractVideoEvidence: 'bg-cyan-100 text-cyan-800',
  scoreConsensus: 'bg-emerald-100 text-emerald-800',
  refreshPriceValue: 'bg-lime-100 text-lime-800',
  generateScenarioPages: 'bg-fuchsia-100 text-fuchsia-800',
  mineKeywords: 'bg-violet-100 text-violet-800',
  generateReviewArticle: 'bg-rose-100 text-rose-800',
  generateComparisonArticle: 'bg-indigo-100 text-indigo-800',
  generateSeoPayload: 'bg-cyan-100 text-cyan-800',
  publishPages: 'bg-lime-100 text-lime-800',
  revalidateAndSitemap: 'bg-fuchsia-100 text-fuchsia-800',
  pingAndIndexing: 'bg-pink-100 text-pink-800',
  http_error: 'bg-rose-100 text-rose-800',
  out_of_stock: 'bg-amber-100 text-amber-800',
  canonical_missing: 'bg-amber-100 text-amber-800',
  canonical_mismatch: 'bg-rose-100 text-rose-800',
  route_type_mismatch: 'bg-rose-100 text-rose-800',
  thin_description: 'bg-amber-100 text-amber-800',
  low_signal_copy: 'bg-amber-100 text-amber-800',
  title_path_mismatch: 'bg-rose-100 text-rose-800',
  heading_hierarchy_gap: 'bg-amber-100 text-amber-800',
  heading_depth_excess: 'bg-amber-100 text-amber-800',
  missing_h2_structure: 'bg-amber-100 text-amber-800',
  render_http_error: 'bg-rose-100 text-rose-800',
  missing_canonical_tag: 'bg-amber-100 text-amber-800',
  canonical_tag_mismatch: 'bg-rose-100 text-rose-800',
  missing_meta_description_tag: 'bg-amber-100 text-amber-800',
  missing_og_title: 'bg-amber-100 text-amber-800',
  missing_og_description: 'bg-amber-100 text-amber-800',
  missing_json_ld: 'bg-rose-100 text-rose-800',
  missing_h1: 'bg-rose-100 text-rose-800',
  multiple_h1: 'bg-rose-100 text-rose-800',
  published_page_noindex: 'bg-rose-100 text-rose-800',
  trust_http_error: 'bg-rose-100 text-rose-800',
  machine_entry_invalid_content_type: 'bg-amber-100 text-amber-800',
  machine_entry_missing_field: 'bg-amber-100 text-amber-800',
  trust_missing_canonical_tag: 'bg-amber-100 text-amber-800',
  trust_missing_json_ld: 'bg-amber-100 text-amber-800',
  trust_missing_trust_links: 'bg-amber-100 text-amber-800',
  llms_missing_reference: 'bg-amber-100 text-amber-800',
  trust_origin_unreachable: 'bg-amber-100 text-amber-800',
  render_timeout: 'bg-amber-100 text-amber-800',
  render_audit_error: 'bg-rose-100 text-rose-800',
  'buy-ready': 'bg-emerald-100 text-emerald-800',
  'blocked-no-link': 'bg-rose-100 text-rose-800',
  'blocked-price': 'bg-amber-100 text-amber-800',
  'blocked-evidence': 'bg-orange-100 text-orange-800',
  'blocked-stock': 'bg-rose-100 text-rose-800',
  'blocked-risk': 'bg-red-100 text-red-800',
  high_intent_no_cta: 'bg-amber-100 text-amber-800',
  high_score_no_link: 'bg-rose-100 text-rose-800',
  broken_go_path: 'bg-rose-100 text-rose-800',
  weak_evidence_buy_cta: 'bg-orange-100 text-orange-800',
  overpriced_buy_cta: 'bg-amber-100 text-amber-800',
  out_of_stock_buy_cta: 'bg-rose-100 text-rose-800'
}

const LABELS: Record<string, string> = {
  active: '启用',
  disabled: '停用',
  enabled: '启用',
  revoked: '已撤销',
  queued: '排队中',
  running: '运行中',
  completed: '已完成',
  completed_with_issues: '部分完成',
  partialFailed: '部分失败',
  failed: '失败',
  cancelled: '已取消',
  success: '成功',
  error: '错误',
  warning: '警告',
  skipped: '已跳过',
  draft: '草稿',
  published: '已发布',
  configured: '已配置',
  partial: '需关注',
  missing: '缺失',
  high: '高',
  medium: '中',
  low: '低',
  review: '评测',
  comparison: '对比',
  guide: '指南',
  hero: '主图',
  gallery: '图集',
  manual: '手动',
  partnerboost_amazon: 'PartnerBoost Amazon',
  partnerboost_dtc: 'PartnerBoost DTC',
  resolveAffiliateLink: '解析联盟链接',
  scrapeProductFacts: '抓取商品事实',
  persistMediaAssets: '保存媒体素材',
  normalizeProduct: '归一化商品',
  mineHardcoreIntents: '挖掘高意图需求',
  resolveVideoEntities: '解析视频实体',
  extractVideoEvidence: '提取视频证据',
  scoreConsensus: '计算共识评分',
  refreshPriceValue: '刷新价格价值',
  generateScenarioPages: '生成场景页',
  mineKeywords: '挖掘关键词',
  generateReviewArticle: '生成评测文章',
  generateComparisonArticle: '生成对比文章',
  generateSeoPayload: '生成 SEO 载荷',
  publishPages: '发布页面',
  revalidateAndSitemap: '刷新缓存与站点地图',
  pingAndIndexing: '提交索引',
  http_error: 'HTTP 错误',
  out_of_stock: '缺货',
  canonical_missing: '缺少 canonical',
  canonical_mismatch: 'canonical 不一致',
  route_type_mismatch: '路由类型不一致',
  thin_description: '描述过薄',
  low_signal_copy: '内容信号弱',
  title_path_mismatch: '标题路径不一致',
  heading_hierarchy_gap: '标题层级缺口',
  heading_depth_excess: '标题层级过深',
  missing_h2_structure: '缺少 H2 结构',
  render_http_error: '渲染 HTTP 错误',
  missing_canonical_tag: '缺少 canonical 标签',
  canonical_tag_mismatch: 'canonical 标签不一致',
  missing_meta_description_tag: '缺少描述标签',
  missing_og_title: '缺少 OG 标题',
  missing_og_description: '缺少 OG 描述',
  missing_json_ld: '缺少 JSON-LD',
  missing_h1: '缺少 H1',
  multiple_h1: '多个 H1',
  published_page_noindex: '已发布但 noindex',
  trust_http_error: '信任页 HTTP 错误',
  machine_entry_invalid_content_type: '机器入口类型异常',
  machine_entry_missing_field: '机器入口字段缺失',
  trust_missing_canonical_tag: '信任页缺少 canonical',
  trust_missing_json_ld: '信任页缺少 JSON-LD',
  trust_missing_trust_links: '信任链接缺失',
  llms_missing_reference: 'LLMS 引用缺失',
  trust_origin_unreachable: '信任源不可达',
  render_timeout: '渲染超时',
  render_audit_error: '渲染审计错误',
  'buy-ready': 'buy-ready',
  'blocked-no-link': 'blocked-no-link',
  'blocked-price': 'blocked-price',
  'blocked-evidence': 'blocked-evidence',
  'blocked-stock': 'blocked-stock',
  'blocked-risk': 'blocked-risk',
  high_intent_no_cta: '高意图无 CTA',
  high_score_no_link: '高分无链接',
  broken_go_path: '断裂跳转',
  weak_evidence_buy_cta: '弱证据购买 CTA',
  overpriced_buy_cta: '高价购买 CTA',
  out_of_stock_buy_cta: '缺货购买 CTA'
}

function formatValue(value: string) {
  if (LABELS[value]) return LABELS[value]
  return value
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .trim()
}

export function StatusBadge({ value }: { value: string }) {
  return (
    <span
      className={cn(
        'inline-flex rounded-full px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.18em]',
        STYLES[value] || 'bg-slate-100 text-slate-700'
      )}
    >
      {formatValue(value)}
    </span>
  )
}
