import { MetricCard } from '@/components/admin/MetricCard'
import { StatusBadge } from '@/components/admin/StatusBadge'
import { getAdminDashboardSummary } from '@/lib/pipeline'

export default async function AdminDashboardPage() {
  const summary = await getAdminDashboardSummary()

  return (
    <div className="space-y-8 p-6 lg:p-10">
      <div>
        <p className="font-mono text-xs uppercase tracking-[0.28em] text-primary">Workflow Center</p>
        <h1 className="mt-2 font-[var(--font-display)] text-4xl font-semibold tracking-tight">One-click product ingestion to published SEO pages.</h1>
      </div>
      <section className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Affiliate Products" value={summary.totals.affiliateProducts} description="Inventory synced from PartnerBoost or manual imports." />
        <MetricCard label="Products" value={summary.totals.products} description="Normalized product records in the Bes3 database." />
        <MetricCard label="Articles" value={summary.totals.articles} description="Review and comparison pages generated by the pipeline." />
        <MetricCard label="Pipeline Runs" value={summary.totals.runs} description="Total runs recorded for the full content workflow." />
      </section>
      <section className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <div className="rounded-[32px] border border-border bg-white p-8 shadow-panel">
          <p className="font-mono text-xs uppercase tracking-[0.24em] text-primary">Recent Runs</p>
          <div className="mt-6 space-y-4">
            {summary.recentRuns.map((run) => (
              <div key={run.id} className="flex items-center justify-between rounded-[24px] border border-border px-5 py-4">
                <div>
                  <p className="font-medium">{run.product_name || run.source_link}</p>
                  <p className="text-sm text-muted-foreground">{run.current_stage || 'idle'}</p>
                </div>
                <StatusBadge value={run.status} />
              </div>
            ))}
          </div>
        </div>
        <div className="rounded-[32px] border border-border bg-white p-8 shadow-panel">
          <p className="font-mono text-xs uppercase tracking-[0.24em] text-primary">Fresh Inventory</p>
          <div className="mt-6 space-y-4">
            {summary.recentAffiliateProducts.map((product) => (
              <div key={product.id} className="rounded-[24px] border border-border px-5 py-4">
                <p className="font-medium">{product.product_name || product.promo_link}</p>
                <p className="text-sm text-muted-foreground">{product.platform}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}
