import Link from 'next/link'
import { ArrowRight, Boxes, FileText, GitBranch, Settings, Wand2 } from 'lucide-react'
import { MetricCard } from '@/components/admin/MetricCard'
import { StatusBadge } from '@/components/admin/StatusBadge'
import { getArticlePath } from '@/lib/article-path'
import { formatMerchantSource } from '@/lib/merchant-links'
import { getAdminDashboardSummary, getPipelineWorkerRuntimeConfig } from '@/lib/pipeline'

function getHealthTone(count: number) {
  return count === 0 ? 'border-emerald-200 bg-emerald-50/80' : 'border-amber-200 bg-amber-50/80'
}

export default async function AdminDashboardPage() {
  const [summary, workerConfig] = await Promise.all([getAdminDashboardSummary(), Promise.resolve(getPipelineWorkerRuntimeConfig())])

  return (
    <div className="space-y-8 p-6 lg:p-10">
      <section className="overflow-hidden rounded-[2.25rem] bg-[linear-gradient(135deg,#0f172a_0%,#1d4ed8_55%,#0f766e_100%)] p-8 text-white shadow-[0_35px_80px_-45px_rgba(15,23,42,0.8)] lg:p-10">
        <div className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr]">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.32em] text-emerald-200/80">Workflow Center</p>
            <h1 className="mt-4 max-w-3xl font-[var(--font-display)] text-4xl font-black tracking-tight text-white sm:text-5xl">
              Operate the Bes3 buying-guide engine from one internal control layer.
            </h1>
            <p className="mt-4 max-w-2xl text-sm leading-8 text-slate-200">
              Sync affiliate inventory, normalize product facts, generate review and comparison pages, and publish updates without exposing pipeline language on the consumer-facing site.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
            <div className="rounded-[1.75rem] border border-white/12 bg-white/10 p-5 backdrop-blur-sm">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-slate-200/85">Worker Runtime</p>
              <div className="mt-4 flex items-end justify-between gap-4">
                <div>
                  <p className="text-3xl font-black">{workerConfig.concurrency}</p>
                  <p className="mt-1 text-sm text-slate-200/75">Concurrent jobs</p>
                </div>
                <StatusBadge value={workerConfig.enabled ? 'configured' : 'missing'} />
              </div>
              <p className="mt-4 text-sm text-slate-200/80">Polling every {workerConfig.pollMs}ms keeps generation work moving without blocking editor operations.</p>
            </div>

            <div className="rounded-[1.75rem] border border-white/12 bg-white/10 p-5 backdrop-blur-sm">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-slate-200/85">High-Value Actions</p>
              <div className="mt-4 grid gap-3">
                <Link href="/admin/products" className="inline-flex items-center justify-between rounded-[1rem] bg-white/10 px-4 py-3 text-sm font-medium text-white transition-colors hover:bg-white/15">
                  Product workspace
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link href="/admin/settings" className="inline-flex items-center justify-between rounded-[1rem] bg-white/10 px-4 py-3 text-sm font-medium text-white transition-colors hover:bg-white/15">
                  Runtime settings
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Affiliate Products" value={summary.totals.affiliateProducts} description="Inventory synced from PartnerBoost or manual imports." />
        <MetricCard label="Products" value={summary.totals.products} description="Normalized product records in the Bes3 database." />
        <MetricCard label="Articles" value={summary.totals.articles} description="Review and comparison pages generated by the pipeline." />
        <MetricCard label="Pipeline Runs" value={summary.totals.runs} description="Total runs recorded for the full content workflow." />
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <div className="rounded-[2rem] border border-slate-200/70 bg-white/90 p-8 shadow-[0_32px_70px_-40px_rgba(15,23,42,0.32)]">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Content Health</p>
              <h2 className="mt-3 text-2xl font-black tracking-tight text-slate-950">Quality signals for the public buying experience</h2>
            </div>
            <StatusBadge value={summary.contentHealth.staleArticleCount === 0 && summary.contentHealth.articlesMissingVisual === 0 ? 'configured' : 'partial'} />
          </div>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <div className={`rounded-[1.5rem] border p-5 ${getHealthTone(summary.contentHealth.productsMissingHero)}`}>
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-500">Products With Live Price</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.productsWithLivePrice}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">Products that currently have both price data and a merchant destination.</p>
            </div>
            <div className={`rounded-[1.5rem] border p-5 ${getHealthTone(summary.contentHealth.productsMissingHero)}`}>
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-500">Products Missing Hero</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.productsMissingHero}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">These products weaken cards, deal modules, and trust on public pages.</p>
            </div>
            <div className={`rounded-[1.5rem] border p-5 ${getHealthTone(summary.contentHealth.articlesMissingVisual)}`}>
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-500">Articles Missing Visuals</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.articlesMissingVisual}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">Published pages that currently lack both article hero media and fallback product hero media.</p>
            </div>
            <div className={`rounded-[1.5rem] border p-5 ${getHealthTone(summary.contentHealth.productsMissingCategory)}`}>
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-500">Products Missing Category</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.productsMissingCategory}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">Category gaps reduce directory quality, search routing, and newsletter relevance.</p>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-[2rem] border border-slate-200/70 bg-white/90 p-8 shadow-[0_32px_70px_-40px_rgba(15,23,42,0.32)]">
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Lifecycle Risk</p>
                <h2 className="mt-3 text-2xl font-black tracking-tight text-slate-950">Pages that need a refresh</h2>
              </div>
              <StatusBadge value={summary.staleArticles.length ? 'partial' : 'configured'} />
            </div>
            <div className="mt-6 space-y-4">
              {summary.staleArticles.length ? (
                summary.staleArticles.map((article) => (
                  <Link
                    key={article.id}
                    href={getArticlePath(article.type, article.slug)}
                    target="_blank"
                    className="block rounded-[1.5rem] border border-slate-200/80 bg-slate-50/70 px-5 py-4 transition-colors hover:border-emerald-200 hover:bg-emerald-50/60"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <p className="font-semibold text-slate-950">{article.title}</p>
                        <p className="mt-1 text-sm text-slate-500">{article.type} · Last reviewed {article.lastReviewedAt ? new Date(article.lastReviewedAt).toLocaleDateString() : 'unknown'}</p>
                      </div>
                      <div className="rounded-full bg-white px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">
                        {article.ageDays}d stale
                      </div>
                    </div>
                  </Link>
                ))
              ) : (
                <div className="rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/70 px-5 py-10 text-center text-sm text-slate-500">
                  No stale public pages right now.
                </div>
              )}
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-1">
            <div className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Audience Capture</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.newsletterSubscribers}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">Email subscribers currently stored in the Bes3 CRM table.</p>
            </div>
            <div className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Preference-Aware Leads</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.contentHealth.targetedSubscribers}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">Subscribers now stored with explicit alert intent for future lifecycle flows.</p>
            </div>
            <div className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Merchant Clicks</p>
              <p className="mt-3 text-3xl font-black text-slate-950">{summary.conversionSignals.totalMerchantClicks}</p>
              <p className="mt-2 text-sm leading-7 text-slate-600">{summary.conversionSignals.merchantClicksLast7Days} tracked over the last 7 days.</p>
            </div>
            <div className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)]">
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Top Exit Surface</p>
              <p className="mt-3 text-2xl font-black text-slate-950">
                {summary.conversionSignals.topMerchantSource ? formatMerchantSource(summary.conversionSignals.topMerchantSource) : 'No click data yet'}
              </p>
              <p className="mt-2 text-sm leading-7 text-slate-600">
                {summary.conversionSignals.topMerchantSource ? `${summary.conversionSignals.topMerchantSourceClicks} clicks from the strongest public CTA surface.` : 'Once buyers start clicking through, Bes3 will surface the strongest path here.'}
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <div className="rounded-[2rem] border border-slate-200/70 bg-white/90 p-8 shadow-[0_32px_70px_-40px_rgba(15,23,42,0.32)]">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Recent Runs</p>
              <h2 className="mt-3 text-2xl font-black tracking-tight text-slate-950">Live workflow activity</h2>
            </div>
            <GitBranch className="h-5 w-5 text-slate-400" />
          </div>

          <div className="mt-6 space-y-4">
            {summary.recentRuns.length ? (
              summary.recentRuns.map((run) => (
                <div key={run.id} className="grid gap-4 rounded-[1.5rem] border border-slate-200/80 bg-slate-50/70 px-5 py-4 md:grid-cols-[1fr_auto] md:items-center">
                  <div>
                    <p className="font-semibold text-slate-950">{run.product_name || run.source_link}</p>
                    <p className="mt-1 text-sm text-slate-500">{run.current_stage || 'Idle'} · Attempt {run.attempt_count}</p>
                    <p className="mt-2 text-xs uppercase tracking-[0.18em] text-slate-400">
                      Updated {new Date(run.updated_at).toLocaleString()}
                    </p>
                  </div>
                  <StatusBadge value={run.status} />
                </div>
              ))
            ) : (
              <div className="rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/70 px-5 py-10 text-center text-sm text-slate-500">
                No pipeline activity has been recorded yet.
              </div>
            )}
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-[2rem] border border-slate-200/70 bg-white/90 p-8 shadow-[0_32px_70px_-40px_rgba(15,23,42,0.32)]">
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Fresh Inventory</p>
                <h2 className="mt-3 text-2xl font-black tracking-tight text-slate-950">Latest affiliate imports</h2>
              </div>
              <Boxes className="h-5 w-5 text-slate-400" />
            </div>

            <div className="mt-6 space-y-4">
              {summary.recentAffiliateProducts.length ? (
                summary.recentAffiliateProducts.map((product) => (
                  <div key={product.id} className="rounded-[1.5rem] border border-slate-200/80 bg-slate-50/70 px-5 py-4">
                    <p className="font-semibold text-slate-950">{product.product_name || product.promo_link}</p>
                    <p className="mt-1 text-sm text-slate-500">{product.platform}</p>
                  </div>
                ))
              ) : (
                <div className="rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/70 px-5 py-10 text-center text-sm text-slate-500">
                  No synced products yet.
                </div>
              )}
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-3 xl:grid-cols-1">
            <Link href="/admin/products" className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)] transition-transform hover:-translate-y-0.5">
              <Boxes className="h-5 w-5 text-primary" />
              <h3 className="mt-4 text-lg font-semibold text-slate-950">Product Workspace</h3>
              <p className="mt-2 text-sm leading-7 text-slate-600">Open the queue that turns affiliate URLs into normalized product pages.</p>
            </Link>
            <Link href="/admin/articles" className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)] transition-transform hover:-translate-y-0.5">
              <FileText className="h-5 w-5 text-primary" />
              <h3 className="mt-4 text-lg font-semibold text-slate-950">Editorial Output</h3>
              <p className="mt-2 text-sm leading-7 text-slate-600">Review generated review, comparison, and guide content before it reaches the public site.</p>
            </Link>
            <Link href="/admin/settings" className="rounded-[1.75rem] border border-slate-200/70 bg-white/90 p-6 shadow-[0_26px_60px_-38px_rgba(15,23,42,0.26)] transition-transform hover:-translate-y-0.5">
              <Settings className="h-5 w-5 text-primary" />
              <h3 className="mt-4 text-lg font-semibold text-slate-950">Runtime Settings</h3>
              <p className="mt-2 text-sm leading-7 text-slate-600">Adjust AI providers, proxy pools, media storage, and SEO environment values.</p>
            </Link>
          </div>
        </div>
      </section>

      <section className="rounded-[2rem] border border-slate-200/70 bg-white/90 p-8 shadow-[0_32px_70px_-40px_rgba(15,23,42,0.32)]">
        <div className="flex items-center gap-3">
          <Wand2 className="h-5 w-5 text-primary" />
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-primary">Product Principle</p>
            <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">The admin is internal. The public site is buyer-facing.</h2>
          </div>
        </div>
        <p className="mt-4 max-w-4xl text-sm leading-8 text-slate-600">
          Keep dashboard language operational and precise here, but keep the consumer site focused on shortlists, comparisons, deep dives, and buying confidence. That separation is now reflected in the shell and page hierarchy.
        </p>
      </section>
    </div>
  )
}
